server:
  port: 8000

spring:
  application:
    name:
      service-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        namespace: test
  config:
    import:
      - nacos:service-order.properties?group=test_group
  profiles:
    include: feign

logging:
  level:
    com.fujiuyi.order.feign:  debug

